gradle/build.gradle, tests/smoke-gradle.yaml
The gradle test takes 18 minutes to complete, occasionally hitting the timeout. There's not a benefit to having such a large test I think, so I've removed some of the dependencies. I tried keeping a variety of different version specifications.
=> slim down the gradle test

README.md
Calling out test regeneration a bit more by creating a section.
=> add more info on regenerating tests

tests/smoke-bundler.yaml
@deivid-rodriguez I might need your expertise to figure out why Bundler in particular is so good at getting around the proxy cache!
=> update bundler expectation to fix test

tests/smoke-go.yaml
supports https://github.com/dependabot/dependabot-core/pull/6713
=> update to support Go pseudo-versions

tests/smoke-go.yaml
This supports https://github.com/dependabot/dependabot-core/pull/6658
=> update for Go-mod version gathering

.github/workflows/cache-all.yml, .github/workflows/cache-one.yml, .github/workflows/refresh-artifacts.yml, .github/workflows/smoke.yml, tests/smoke-go-close-pr.yaml, tests/smoke-go-security.yaml, tests/smoke-go-update-pr.yaml
This adds test coverage around updating PRs, closing PRs, and security updates.
=> add more updater scenarios

tests/smoke-go.yaml
Picks up the changes due to https://github.com/dependabot/dependabot-core/pull/6723
=> regenerate Go smoke test

tests/smoke-cargo.yaml
For PR: https://github.com/dependabot/dependabot-core/pull/7080
=> cargo: add new call to package_manager_version

tests/smoke-bundler.yaml, tests/smoke-cargo.yaml, tests/smoke-elm.yaml, tests/smoke-go.yaml, tests/smoke-hex.yaml, tests/smoke-npm-remove-transitive.yaml, tests/smoke-pip-compile.yaml, tests/smoke-pip.yaml, tests/smoke-pipenv.yaml, tests/smoke-poetry.yaml, tests/smoke-pub.yaml, tests/smoke-submodules.yaml
This is a companion to https://github.com/dependabot/dependabot-core/pull/7118.
I edited these files manually, hopefully I didn't miss anything!
=> Remove empty release notes from smoke tests

.github/workflows/smoke.yml, script/run-all.sh, tests/smoke-go-group-rules.yaml
Part of https://github.com/github/dependabot-updates/issues/3770
=> Add grouped updates smoke test for go

tests/smoke-pub.yaml
Adjusts the expectations from the changes in https://github.com/dependabot/dependabot-core/pull/7417
=> Sync pub test with changes in latest update

tests/smoke-pnpm.yaml
To pick up the previous change made to the manifest.
This repo always tricks me 😅
=> Update reference to code in PNPM smoke test

actions/action.yml, tests/smoke-actions.yaml
As title, I decided to just add more actions and a group config to our existing smoke test rather than add one more to the overall test rig.
=> Extend the Actions smoke test to include a Group PR

npm/transitive/package-lock.json, npm/transitive/package.json, tests/smoke-npm-group-transitive.yaml
This is a smoke test for indirect dependency grouping. It appears to not be working currently and creates 3 PRs instead of grouping 2 from the `@hoek` group together.
=> indirect dependency grouping

tests/smoke-npm-group-multiple.yaml
Regenerate due to https://github.com/dependabot/dependabot-core/pull/7796
=> refresh due to table change

tests/smoke-npm-group-rules.yaml, tests/smoke-npm.yaml
The smoke tests started failing about 8 hours ago. I don't see an obvious reason for it. Looks like it wasn't fully cached. So I've regenerated the failing tests and will recache the calls.
=> refresh npm smoke tests

tests/smoke-swift.yaml
This might indicate it avoids our caching methods so might require further analysis if it keeps happening.
=> regenerate swift test since it became uncached

nuget/resolvability/A/A.csproj, nuget/resolvability/A/Program.cs, nuget/resolvability/B/B.csproj, nuget/resolvability/B/Program.cs, nuget/resolvability/DependabotRepro.sln, nuget/resolvability/Directory.Packages.props, tests/smoke-nuget-resolvability.yaml
I'd expect this to fail, but start passing with https://github.com/dependabot/dependabot-core/pull/8179.
=> Add a new smoke test for nuget

tests/smoke-bundler-group-multidir.yaml, tests/smoke-cargo-group-multidir.yaml, tests/smoke-go-group-multidir.yaml, tests/smoke-go-group-security.yaml, tests/smoke-gradle-group-multidir.yaml, tests/smoke-maven-group-multidir.yaml, tests/smoke-npm-group-multidir.yaml, tests/smoke-nuget-group-multidir.yaml, tests/smoke-pip-group-multidir.yaml
Needed after https://github.com/dependabot/dependabot-core/pull/8494
I don't have these hooked up in Core yet.
=> regenerate multidir tests

README.md
It's easy to create a new test but requires a specific procedure to be successful, so I added documentation for that.
=> instruct how to create a new test

tests/smoke-go-group-security.yaml
Missed one as it has a slightly different name than the others.
=> regenerate grouped security test

tests/smoke-docker-version-multidir.yaml, tests/smoke-go-version-multidir.yaml
A couple of the tests were targeted at a feature branch, pending being checked into main.  This corrects those branches.
=> Re-target new tests to the main branch

script/regen.sh, script/run-all.sh, script/run-one.sh, tests/smoke-nuget-central-package-management.yaml, tests/smoke-nuget-compatible-version.yaml, tests/smoke-nuget-dirs-proj.yaml, tests/smoke-nuget-group-multidir.yaml, tests/smoke-nuget-peer-dependencies.yaml, tests/smoke-nuget-potential-downgrade.yaml, tests/smoke-nuget-props-and-targets.yaml, tests/smoke-nuget-resolvability.yaml, tests/smoke-nuget-sdk-implicit-deps.yaml, tests/smoke-nuget-transitive-pinning.yaml, tests/smoke-nuget-version-multidir.yaml, tests/smoke-nuget-version-property.yaml, tests/smoke-nuget.yaml
I ran:
```
script/regen.sh tests/*nuget*
```
=> regenerate nuget ecosystem tests

tests/smoke-nuget-props-and-targets.yaml
I'm wondering if https://github.com/dependabot/dependabot-core/pull/8945 helped here, so I regenerated the test again.
=> regenerate nuget test that is out of order

tests/smoke-go-group-security.yaml, tests/smoke-gradle-group-multidir.yaml
Following https://github.com/dependabot/smoke-tests/pull/182, I missed these two tests!
=> remove most multidir test groups

tests/smoke-bundler-group-multidir.yaml
I think I missed this one in https://github.com/dependabot/smoke-tests/pull/173
=> regen bundler test

nuget/multi-dir/bar/project.csproj, nuget/multi-dir/foo/project.csproj, tests/smoke-nuget-version-multidir.yaml
This adds a dependency to each directory of the NuGet multi-dir test to exercise the issue mentioned in https://github.com/dependabot/dependabot-core/pull/9228.
=> improve nuget multidir test

tests/smoke-nuget-group-multidir.yaml, tests/smoke-nuget-version-multidir.yaml
Updates smoke tests to conform with dependabot/dependabot-core#9384
=> update smoke test messages

tests/smoke-python-version-multidir.yaml
We probably want to recache this at some point as well.
=> fix python smoke tests by adjusting ignores

tests/smoke-composer.yaml
Updated the smoke test output to reflect the functionality change made for not respecting minor patch updates filter.
=> Updated the smoke test output to reflect the functionalitly change made for not respecting minor patch updates filter.

tests/smoke-composer.yaml
Reverts dependabot/smoke-tests#207
The PR above seems to be changing the composer test into an actions test. Let's revert it to get back to normal and then proceed with fixing it.
=> Revert "Updated the smoke test output to reflect the functionalitly change made for not respecting minor patch updates filter."

README.md
=> docs: remove statement about external contributions

tests/smoke-nuget-transitive-and-top-level-deps.yaml
This is to support https://github.com/dependabot/dependabot-core/pull/10449
=> update smoke test commit

tests/smoke-nuget-central-package-management.yaml, tests/smoke-nuget-compatible-version.yaml, tests/smoke-nuget-dirs-proj.yaml, tests/smoke-nuget-group-multidir.yaml, tests/smoke-nuget-peer-dependencies.yaml, tests/smoke-nuget-potential-downgrade.yaml, tests/smoke-nuget-props-and-targets.yaml, tests/smoke-nuget-resolvability.yaml, tests/smoke-nuget-sdk-implicit-deps.yaml, tests/smoke-nuget-transitive-and-top-level-deps.yaml, tests/smoke-nuget-transitive-pinning.yaml, tests/smoke-nuget-version-multidir.yaml, tests/smoke-nuget-version-property.yaml, tests/smoke-nuget.yaml
This PR corresponds to https://github.com/dependabot/dependabot-core/pull/10472
=> revert smoke test additional metadata

.github/workflows/smoke.yml, tests/smoke-maven-group-multidir.yaml
Reverts dependabot/smoke-tests#228
=> Revert "Bump version in maven security advisory"

tests/smoke-nuget-central-package-management.yaml, tests/smoke-nuget-compatible-version.yaml, tests/smoke-nuget-dirs-proj.yaml, tests/smoke-nuget-group-multidir.yaml, tests/smoke-nuget-lockfile.yaml, tests/smoke-nuget-peer-dependencies.yaml, tests/smoke-nuget-potential-downgrade.yaml, tests/smoke-nuget-props-and-targets.yaml, tests/smoke-nuget-resolvability.yaml, tests/smoke-nuget-sdk-implicit-deps.yaml, tests/smoke-nuget-transitive-and-top-level-deps.yaml, tests/smoke-nuget-transitive-pinning.yaml, tests/smoke-nuget-version-multidir.yaml, tests/smoke-nuget-version-property.yaml, tests/smoke-nuget.yaml
This PR is required for dependabot/dependabot-core#10597 and should not be merged alone.  Because of that, this PR will remain as a draft.
=> update smoke tests to correspond to new nuget reporting

tests/smoke-npm-group-rules.yaml, tests/smoke-npm-group-semver.yaml, tests/smoke-npm-group-transitive.yaml, tests/smoke-npm-version-multidir.yaml, tests/smoke-npm.yaml
Related PR : https://github.com/dependabot/dependabot-core/pull/11299
=> More updates to smoke test logs related core pack fixes

tests/smoke-npm-group-rules.yaml
Related to : https://github.com/dependabot/dependabot-core/pull/11299
=> Update to smoke test logs.

tests/smoke-npm-group-multidir.yaml, tests/smoke-npm-group-multiple.yaml, tests/smoke-npm-group-rules.yaml, tests/smoke-npm-group-semver.yaml, tests/smoke-npm-group-transitive.yaml, tests/smoke-npm-remove-transitive.yaml, tests/smoke-npm-version-multidir.yaml, tests/smoke-npm.yaml
Reverting the smoketest related to corepack changes.
=> Reverting the smoketest related to corepack changes.

tests/smoke-nuget-potential-downgrade.yaml
This is a pre-emptive update to a smoke test for a future PR in dependabot-core.
=> updated patched version to a version that actually exists

tests/smoke-npm-group-rules.yaml, tests/smoke-npm-group-semver.yaml, tests/smoke-npm.yaml
[call-bind-apply-helpers](https://www.npmjs.com/package/call-bind-apply-helpers) has released version 1.0.2, so we need to update our tests
=> Update call-bind-apply-helpers to 1.0.2

pipenv/Pipfile, pipenv/Pipfile.lock, tests/smoke-python-pipenv.yaml
Reverts dependabot/smoke-tests#260
=> Revert "Remove django dependency as it's subdependencies require deprecated python 3.8"

tests/smoke-npm-group-rules.yaml, tests/smoke-npm-group-semver.yaml, tests/smoke-npm.yaml
This updates the NPM tests that are still failing on main.
=> Fix failing npm tests

tests/smoke-bundler-group-vendoring.yaml, tests/smoke-bundler.yaml, tests/smoke-go-security.yaml, tests/smoke-go-update-pr.yaml, tests/smoke-npm-yarn-berry.yaml
Companion to https://github.com/dependabot/dependabot-core/pull/11760
The cargo failures are unrelated.
=> remove mode, only set explicitly

tests/smoke-bundler-security-subdep.yaml
This fix is related to below CI run failure
https://github.com/dependabot/dependabot-core/actions/runs/15616005870/job/43988887604?pr=12438
=> Smoke test fixture related to bundler private registry cooldown.

tests/smoke-npm-group-multiple.yaml, tests/smoke-npm-group-rules.yaml
These tests fell out of sync so I am regenerating them and recaching the network calls.
=> regenerate failing tests

tests/smoke-vcpkg-builtin-baseline.yaml, vcpkg/builtin-baseline/vcpkg.json
Related:
- https://github.com/dependabot/dependabot-core/issues/7644
- https://github.com/dependabot/cli/pull/462
- https://github.com/dependabot/dependabot-core/pull/12491
=> Add `vcpkg` smoke tests

tests/smoke-npm-group-multiple.yaml, tests/smoke-npm-group-semver.yaml, tests/smoke-npm-group-transitive.yaml
You can find details in the following PR: 
- https://github.com/dependabot/dependabot-core/pull/12583
=> Fix for NPM Detection Change
