- tests/smoke-poetry.yaml
`poetry` `1.2.1` no longer generates this line that was present in `1.2.0`.
I'm not 100% positive, but I _think_ that might be the result of https://github.com/python-poetry/poetry/pull/6389.
Details here: https://github.com/dependabot/dependabot-core/pull/5746#issuecomment-1253773172
> Update test to conform to `poetry` `1.2.1`

- tests/smoke-npm-remove-transitive.yaml
The changes in https://github.com/dependabot/dependabot-core/pull/5816 mean that we expect the source to be populated now. Adjust this test expectation to match.
> Fix npm requirement source

- tests/smoke-actions.yaml
- tests/smoke-go.yaml
- tests/smoke-pub.yaml
- tests/smoke-terraform.yaml
Bumping due to https://github.com/dependabot/dependabot-core/pull/5843
The commits were in the past before the reorganization so now that they are going to be fixed these matter again!
> pin to latest commits

- tests/smoke-bundler.yaml
The branch will be left blank if not explicit in the Gemfile.
Needed to get https://github.com/dependabot/dependabot-core/pull/6149 green.
> Don't hardcode master branch in dependencies

- tests/smoke-bundler.yaml
- tests/smoke-yarn-berry.yaml
Once https://github.com/dependabot/dependabot-core/pull/6141 is merged we will need this to get smoke tests to pass again.
> Adding mode to PR output

- .github/dependabot.yml
In this case the non-test stuff is the GitHub actions workflows... 😀
> Enable Dependabot for the non-test stuff

- tests/smoke-go.yaml
We do this by default unless a job is configured to use private dependencies. This should make the test run faster.
> Enable using public go module proxy

- tests/smoke-gradle.yaml
In https://github.com/dependabot/dependabot-core/pull/6526, the display name for Gradle was updated to include the full name. See that PR for rationale.
Updated the smoke test by finding the image name from: https://github.com/dependabot/dependabot-core/actions/runs/4034930902/attempts/1#summary-10953476551
And then running:
```shell
dependabot --updater-image ghcr.io/dependabot/dependabot-updater-gradle:5eff30823a1eb0aba02f2267d14427a8bb547414 test -f tests/smoke-gradle.yaml -o tests/smoke-gradle.yaml
```
And committing the diff.
> Update Gradle smoke test to include full name

- yarn-berry/yarn.lock
Run `yarn install --mode=update-lockfile` on the yarn berry setup creates some source control changes, because the requirement in the package.json file is out of the with locked requirements.
We should make sure to start off with a clean slate and this is what this PR does.
> Ensure sane starting point for yarn berry test

- tests/smoke-nuget.yaml
A little over a month ago, all of our tests started failing because Action Artifacts are only retained for 90 days (TODO I need to fix that so we don't have this problem again). 
While regenerating this Nuget test, I noticed the version we were testing against was yanked, so I updated it. I picked the wrong version and didn't notice, because 6.2.1 is also yanked, so this test is rather... bad.
Bumping the ignore up to 6.2.2 makes a PR and a better test 😄
> make a better Nuget test

- .github/workflows/cache-one.yml
Main change is to update the workflow to allow updating the cache even if tests fail.
Motivation is to get out of (I think) a chicken-and-egg issue while trying to get #28 green because tests there will fail because cache is out of date, and cache cannot be updated because tests fail.
Unrelated to this, I wonder if we could manage the cache within the main workflow itself.
> Improve "Cache one" workflow

- .github/workflows/refresh-artifacts.yml
We use the Actions Artifacts to store the cache of the tests, but that expires after 90 days. This has already happened once where suddenly many of the caches were gone and we had to regenerate all the tests and caches again. This isn't a huge deal, but we don't need surprises. 
My cheeky solution is to run this job weekly where it downloads and then uploads the cache, keeping it from expiring. 
I set it to weekly in hopes that if it breaks we have more of a chance of catching it before the 90 days are up.
> prevent Artifacts from expiring after 90 days

- bundler/Gemfile
- bundler/Gemfile.lock
When we re-arranged the project into subfolders, we removed some references to a `gemspec` and I think some submodules, so this PR just cleans up the Gemfile/Gemfile.lock so they are usable for new tests.
I haven't modified the existing tests as they are essentially shrink-wrapped from this change.
> Remove gemspec reference and rebundle

- .github/workflows/cache-all.yml
- .github/workflows/cache-one.yml
- .github/workflows/refresh-artifacts.yml
- .github/workflows/smoke.yml
- tests/smoke-bundler-grouped.yaml
This PR adds a regression test for the feature/experiment introduced in https://github.com/dependabot/dependabot-core/pull/6884
Before this can merge, #46 needs to be merged as I used it as the base sha for this test and https://github.com/dependabot/dependabot-core/pull/6884 needs to merge in core so this test can be expected to pass when used against the core repo.
> Add a smoke test for a grouped bundler PR

- tests/smoke-cargo.yaml
https://github.com/dependabot/dependabot-core/pull/6995
The new version got around the cache.
> regenerate Cargo smoke test due to Rust/Cargo version bump

- tests/smoke-cargo.yaml
I added `rand` and `iota` dependencies as two different Git source URLs to ensure they stay working and exercise more code.
Also switched `time` to a pre-release. 
It's probably best to just review the [output](https://github.com/dependabot/smoke-tests/blob/cb9b6745de1220a6e33410367ec6571bcbb787e9/tests/smoke-cargo.yaml) and not the diff, and compare to [the manifests](https://github.com/dependabot/smoke-tests/tree/main/cargo) to make sure the PRs created make sense. 
The 4 PRs I see created are:
- Bump time from 0.3.0-alpha-2 to 0.3.20 in /cargo
- Bump regex from 1.6.0 to 1.7.3 in /cargo
- Bump rand from 0.8.4 to 0.8.5 in /cargo
- Bump itoa from 1.0.5 to 1.0.6 in /cargo
> improve Cargo smoke tests by adding git sources

- tests/smoke-bundler-grouped.yaml
As title, the ignore condition in the file was copypasta from a different ecosystem I didn't really vet originally as grouped updates didn't consume `ignore_conditions`.
As of https://github.com/dependabot/dependabot-core/pull/7091, they do so this is breaking on that PR.
I have a follow up PR which ignores the current version of rubocop to make sure it ignores actually work, but it'll break for all SHAs until https://github.com/dependabot/dependabot-core/pull/7091 merges, so it can follow up after.
> Remove a malformed ignore condition

- tests/smoke-bundler-group-rules.yaml
Adds a bundler grouped update smoke test for a job that has dependency-group rules.
This smoke test also includes an ignore config which grouped updates now supports.
This is different from the existing bundler grouped update smoke test because that tests the default `group-all` behavior that appears for jobs _without_ a dependency-group rule.
> Add a bundler grouped update smoke test for a job that has dependency-group rules

- .github/workflows/cache-all.yml
- .github/workflows/cache-one.yml
- .github/workflows/refresh-artifacts.yml
- .github/workflows/smoke.yml
Adds the `bundler-group-rules` to the smoke test workflows
Is there anything I need to do prior to merging this?
> Add bundler-group-rules smoke test

- tests/smoke-bundler-group-rules.yaml
- tests/smoke-bundler-grouped.yaml
See: https://github.com/dependabot/dependabot-core/pull/7137
When this core PR merges, it will break the smoke tests as they will expect the old titles.
This updates the smoke tests using the new strategy, my plan is to merge the core PR and then immediately merge this and re-cache those tests so other PRs are tested against the new strategy shortly after it hits `main`.
> Re-align grouped update smoke tests with a change in PR message strategy

- tests/smoke-cargo.yaml
- tests/smoke-go-security.yaml
- tests/smoke-go.yaml
- tests/smoke-gradle-version-catalog.yaml
- tests/smoke-yarn.yaml
This realigns these smoke tests with https://github.com/dependabot/cli/pull/103 released in cli version v1.20.1, which changed `dependency-group` to be omitted if empty to align with the API's expectations.
This just walks back some changes made to smoke tests that needed to be refreshed when v1.20.0 was forcing this key to be put in output files.
> Remove dependency-groups from go and cargo tests, remove grouped-update flag

- tests/smoke-bundler-group-rules.yaml
dependabot/dependabot-core#7247 added handling for grouped PR intros, which caused the bundler-group-rules e2e test to start failing in core. This PR regenerates the smoke test expectations for the new copy. Once this is merged we can re-enable the failing e2e in core.
> Update bundler smoke test for updated grouped PR intros

- pnpm/package.json
- pnpm/pnpm-lock.yaml
- tests/smoke-pnpm.yaml
I merged the previous PNPM smoke test too soon, and then found that the core PR is not fully fixing the problem.
While I work on fully fixing the issue, I'm leaving a passing PNPM spec in place, so that smoke tests still pass and we at least have a basic smoke test for PNPM.
> Simplify PNPM smoke test

- tests/smoke-pub.yaml
see https://github.com/dependabot/dependabot-core/pull/7265
Summary:
```
updater | +------------------------------------------------------------------------------+
updater | |                     Changes to Dependabot Pull Requests                      |
updater | +---------+--------------------------------------------------------------------+
updater | | created | collection ( from 1.17.0 to 1.17.1 )                               |
updater | | created | fixnum ( from 0.10.11 to 1.1.0 ), protobuf ( from 1.1.4 to 2.1.0 ) |
updater | | created | http ( from 0.13.2 to 0.13.6 )                                     |
updater | | created | path ( from 1.8.1 to 1.8.3 )                                       |
updater | | created | retry ( from 2.0.0 to 3.1.1 ) …
```
> update pub test with latest PR

- tests/smoke-npm-group-rules.yaml
Update the grouped npm smoke test to include the newline added in https://github.com/dependabot/dependabot-core/pull/7401
> Update the npm group smoke test

- tests/smoke-yarn-berry.yaml
- tests/smoke-yarn.yaml
It looks like our yarn caches have moved ahead from the checked-in test files, so this PR refreshes the two failing tests.
The yarn specs may still fail on this branch, if they do we will need to run `cache-one` for:
- smoke-yarn.yml
- smoke-yarn-berry.yml
Afterwards, both tests should pass and we can merge for main to go 🍏
> Update the yarn smoke tests to latest versions

- pnpm/package.json
> Lock PNPM version in smoke test

- .github/workflows/cache-all.yml
- .github/workflows/cache-one.yml
- .github/workflows/smoke.yml
Update our cache workflows to add a missing test - we haven't needed to recache these yet, but this will ensure we can when we need to
> Ensure we have the go-group-rules test in our cache workflows

- tests/smoke-bundler-group-rules.yaml
- tests/smoke-bundler-group-vendoring.yaml
- tests/smoke-bundler.yaml
- tests/smoke-cargo.yaml
- tests/smoke-go-close-pr.yaml
- tests/smoke-go-group-rules.yaml
- tests/smoke-go-security.yaml
- tests/smoke-go-update-pr.yaml
- tests/smoke-go.yaml
- tests/smoke-npm-group-rules.yaml
- tests/smoke-npm-remove-transitive.yaml
- tests/smoke-npm.yaml
- tests/smoke-pnpm.yaml
- tests/smoke-yarn-berry-workspaces.yaml
- tests/smoke-yarn-berry.yaml
- tests/smoke-yarn.yaml
As of https://github.com/dependabot/dependabot-core/pull/7517 we're now using a `record_ecosystem_versions` endpoint instead of `record_package_manager_versions`.
So this updates the test expectations accordingly.
> Migrate to the new `record_ecosystem_versions` endpoint

- .github/workflows/cache-all.yml
- .github/workflows/cache-one.yml
- .github/workflows/list-suites.yml
- .github/workflows/refresh-artifacts.yml
- .github/workflows/smoke.yml
At the risk of overcomplicating things, I thought it might be nice if when adding a new test we didn't have to go to N workflow files and add the new test name.
Using a reusable workflow file, this automatically generates the suites from the test files themselves.
> generate suites automatically and from a reusable workflow

- tests/smoke-composer.yaml
`composer` now records a metric:
* https://github.com/dependabot/dependabot-core/pull/7323
> Update composer test to include metrics

- tests/smoke-maven.yaml
See https://github.com/dependabot/dependabot-core/pull/7146
> Update maven tests to use groupId and artifactId for the dependency name 

- tests/smoke-maven.yaml
> Include groupId in release note summary

- tests/smoke-swift.yaml
The Swift test started failing due to new dependencies being released. Looks like the ignores didn't work cc @deivid-rodriguez. 
Also it's probably not been cached, so I will cache after merging to prevent future failures.
> regenerate swift test

- tests/smoke-swift.yaml
So that names match what Advisories and Dependency Graph use.
This is a companion to https://github.com/dependabot/dependabot-core/pull/7648.
> Use full names for Swift dependencies

- pipenv/Pipfile
- pipenv/Pipfile.lock
Small cleanups to `Pipfile`
- The url is now `pypi.org`.
- Use a newer python
I then did the following:
1. Regenerated `Pipfile.lock` by manually running:
```shell
bin/docker-dev-shell python # in dependabot-core, this ensure we use the proper pipenv version
vi Pipfile # paste contents of Pipfile
pyenv exec pipenv lock
```
2. Create a commit with these changes.
3. Updated the `tests/smoke-pipenv.yaml` input commit to be the commit
that I just modified. 
4. Regenerated test expectations using:
```shell
dependabot test -f tests/smoke-pipenv.yaml -o tests/smoke-pipenv.yaml
```
5. Committed these final results.
> Small cleanups to `Pipfile` / `pipenv` smoke test

- tests/smoke-pip-compile.yaml
I guess the python upgrades let these go higher.
References: https://github.com/dependabot/dependabot-core/actions/runs/5901380694/job/16007458420?pr=7843.
> Add missing pip-compile ignores

- .yamllint.yaml
These files are generated, and they do not match our style. Leave them alone.
> Ignore smoke tests from yamllint check

- .gitignore
- script/run-all.sh
* Don't keep a hardcoded list of smoke tests and loop through all of them automatically instead.
* Allow optionally downloading and using the existing cache of network calls.
> Improve `run-all.sh` script

- tests/smoke-pipenv.yaml
We upgraded pipenv recently and this is the result the new pipenv version gives. We have not received any reports since we ugpraded so I'm assuming this change is actually a bug fix rather than a regression.
This patch was generated using `./script/run-one.sh tests/smoke-pipenv.yaml` from #129.
> Regenerate pipenv smoke tests to match current behavior

- composer/composer.lock
- composer/vendor/phpstan/phpstan-strict-rules/build-cs/composer.lock
- tests/smoke-composer.yaml
This is to support newer versions of Composer. See also https://github.com/dependabot/dependabot-core/pull/8299
> Update Composer `plugin-api-version` to 2.6.0

- tests/smoke-pipenv.yaml
In https://github.com/dependabot/dependabot-core/pull/8312 we'll be migrating to use `pipenv upgrade` under the hood.
This works better, it's simpler, and avoids issues with undesired unrelated transitive dependency upgrades.
However, it has the gotcha that it does not clean up unused dependencies after it's run.
I think this is a more minor issue than what we fix by adopting it, and unlikely to cause problems. I reported upstream [here](https://github.com/pypa/pipenv/issues/6002).
For now, I think the best thing we can do is adapt our expectation.
I checked that this branch is already passing against the pipenv upgrade with https://github.com/dependabot/dependabot-core/pull/8312/commits/1e6f35b76a0ba679ad92e623772f59da6b1df94a.
> Adapt expectation to `pipenv upgrade`

- tests/smoke-go-security.yaml
- tests/smoke-go-update-pr.yaml
There's a bug in the Go FileFetcher that https://github.com/dependabot/dependabot-core/pull/8309 is mitigating, so we need to fix these tests.
> fix Go smoke tests

- .github/workflows/i-am-a-smoke-test.yml
- tests/smoke-actions.yaml
I ran into an issue on https://github.com/dependabot/dependabot-core/pull/8331 that could have been caught sooner if the GitHub Actions smoke test was more realistic. Most (95%) users set up the directory as `/` which automatically picks up `/.github/workflows` files as dependencies. 
So this PR moves the workflow under test into the usual workflows directory. 
I think the reason we separated it before was the other legitimate workflow files interfere somewhat, but since we're pinned to a commit it shouldn't matter too much.
> make actions smoke test more realistic

- tests/smoke-npm-remove-transitive.yaml
- tests/smoke-yarn-berry-workspaces.yaml
Cleans up some feature flags that are no longer necessary.
npm-transitive-dependency-removal was removed in:
https://github.com/dependabot/dependabot-core/pull/8359/
> Remove unused npm feature flags

- .gitignore
I was adding a NuGet smoke test and I was banging my head against the wall because it just wouldn't work.
Turns out my test case included a file named `DependabotRepro.sln`, but did not get committed but it was gitignored.
> Fix ignore rule to not match all files with Dependabot in their name

- tests/smoke-nuget-resolvability.yaml
This PR is to support dependabot/dependabot-core#8511
It is to reflect the different order that dependency files are returned.
> update smoke test to handle reordered dependency files

- .github/workflows/smoke.yml
- script/download-cache.sh
If a test is not cached, it will eventually fail once one of the dependencies gets a new release.
This PR exposes the uncached tests by failing when the artifact download fails, so we can run the cache job before it starts failing.
It might also be wise to automatically run the cache job when merging a new test to main but this seemed like a good first step.
> expose uncached tests

- composer/composer.json
- tests/smoke-composer.yaml
This updates the composer test to include an artifact that points to a directory that is empty which seems to be a common scenario. 
In the future we need to add a directory that has zipped artifacts too.
I also didn't see any Composer tests for path directories so throw that on the todo list as well.
Needs https://github.com/dependabot/dependabot-core/pull/8620 to pass.
> update test to include composer artifacts

- tests/smoke-bundler-group-rules.yaml
- tests/smoke-bundler-group-vendoring.yaml
- tests/smoke-bundler.yaml
New version of Bundler 2.5 makes slightly different network requests that cause our smoke tests cached requests to not be hit, which causes some versions to be bumped further than our expectations.
This is not a problem in Bundler or Dependabot, so easiest way to unblock the upgrade to Bundler 2.5 is to update smoke test expectations.
> Regenerate Bundler smoke test results

- tests/smoke-nuget-central-package-management.yaml
- tests/smoke-nuget-compatible-version.yaml
- tests/smoke-nuget-dirs-proj.yaml
- tests/smoke-nuget-peer-dependencies.yaml
- tests/smoke-nuget-potential-downgrade.yaml
- tests/smoke-nuget-props-and-targets.yaml
- tests/smoke-nuget-sdk-implicit-deps.yaml
- tests/smoke-nuget-transitive-pinning.yaml
- tests/smoke-nuget-version-property.yaml
This resets the target branch for the new nuget tests now that they have been checked in.
> Remove the target branch for nuget tests

- tests/smoke-bundler-group-rules.yaml
- tests/smoke-bundler-group-vendoring.yaml
- tests/smoke-bundler.yaml
@deivid-rodriguez did you happen to recache these after #164? If so then Bundler learned new ways to evade the caching in 2.5 😄
> regenerate bundler smoke tests

- tests/smoke-bundler-group-multidir.yaml
- tests/smoke-cargo-group-multidir.yaml
- tests/smoke-go-group-multidir.yaml
- tests/smoke-go-group-security.yaml
- tests/smoke-go-update-security-multidir.yaml
- tests/smoke-gradle-group-multidir.yaml
- tests/smoke-maven-group-multidir.yaml
- tests/smoke-npm-group-multidir.yaml
- tests/smoke-nuget-group-multidir.yaml
- tests/smoke-python-group-multidir.yaml
In the current Core code these are created on-the-fly but now we want to be able to define them externally.
> adding explicit group definitions to grouped updates

- devcontainers/.devcontainer.json
- devcontainers/.devcontainer/devcontainer-lock.json
- devcontainers/.devcontainer/devcontainer.json
- tests/smoke-devcontainers.yaml
This is the same as #149, but making sure smoke tests uses `dependabot/smoke-tests` instead of an external repo.
> Add smoke tests for devcontainers

- script/run-one.sh
Using source to generate the cache makes the script exit too soon since the script is run in the same shell and explicitly uses `exit`.
> Fix regenerating smoke tests while keeping cache

- tests/smoke-bundler-group-rules.yaml
- tests/smoke-bundler-group-vendoring.yaml
- tests/smoke-bundler.yaml
So that we get more consistent results regardless of rubocop releases.
> Fix ignore condition for bundler group rules test

- tests/smoke-npm-group-multidir.yaml
[Changes to the updater](https://github.com/dependabot/dependabot-core/pull/8803) means it now is picking up that the bump to dummy-pkg-b also bumped dummy-pkg-a since it has a dependency on it.
> update npm multidir based on new logic

- tests/smoke-go-group-multidir.yaml
This requires: https://github.com/dependabot/dependabot-core/pull/8742
I changed the group rule to:
```
- name: go_modules group
rules:
patterns:
- rsc.io/qr
```
This results in 3 PRs:
- One multi-dir grouped PR for rsc.io/qr across both directories
- One single-dir PR for rsc.io/quote in /foo
- One single-dir PR for rsc.io/quote in /bar
> more complex multi-dir example

- tests/smoke-bundler-group-multidir.yaml
- tests/smoke-bundler-group-rules.yaml
- tests/smoke-bundler-group-vendoring.yaml
- tests/smoke-bundler-version-multidir.yaml
- tests/smoke-cargo-group-multidir.yaml
- tests/smoke-cargo-version-multidir.yaml
- tests/smoke-docker-version-multidir.yaml
- tests/smoke-go-group-multidir.yaml
- tests/smoke-go-group-rules.yaml
- tests/smoke-go-group-security.yaml
- tests/smoke-go-version-multidir.yaml
- tests/smoke-gradle-group-multidir.yaml
- tests/smoke-gradle-version-multidir.yaml
- tests/smoke-maven-group-multidir.yaml
- tests/smoke-maven-version-multidir.yaml
- tests/smoke-npm-group-multidir.yaml
- tests/smoke-npm-group-multiple.yaml
- tests/smoke-npm-group-rules.yaml
- tests/smoke-npm-group-semver.yaml
- tests/smoke-npm-group-transitive.yaml
- tests/smoke-npm-version-multidir.yaml
- tests/smoke-nuget-group-multidir.yaml
- tests/smoke-nuget-version-multidir.yaml
- tests/smoke-python-group-multidir.yaml
- tests/smoke-python-version-multidir.yaml
The cleanup involved:
- Setting `grouped-update: true` for all grouped updates
- Removing the unused `credentials-metadata`
- Removing `directory` for multi-dir tests
- Removing unused experiments
> cleanup test inputs

- tests/smoke-bundler-group-multidir.yaml
- tests/smoke-cargo-group-multidir.yaml
- tests/smoke-go-group-multidir.yaml
- tests/smoke-go-update-security-multidir.yaml
- tests/smoke-maven-group-multidir.yaml
- tests/smoke-npm-group-multidir.yaml
- tests/smoke-nuget-group-multidir.yaml
- tests/smoke-python-group-multidir.yaml
In a previous change I added these groups to the multidir tests, but now we're creating default groups for security updates so it's not needed:
- https://github.com/dependabot/dependabot-core/pull/8742
And now in https://github.com/dependabot/dependabot-core/pull/9040 we're going to either need to remove these or set the `applies-to` field.
I'm removing most of them, but adding `applies-to` in `tests/smoke-go-group-multidir.yaml` since it's a more complex scenario.
> remove most multidir test groups

- tests/smoke-actions.yaml
- tests/smoke-composer.yaml
- tests/smoke-go-update-security-multidir.yaml
- tests/smoke-go-update-version-multidir.yaml
- All grouped updates must have `grouped-update: true`
- Either `directory` or `directories` must be specified, but not both!
> found more invalid test inputs, align to recent changes

- tests/smoke-bundler-version-multidir.yaml
The test started failing 17 hours ago, no clear reason why except a new version of rack was released. I'll recache the test.
> fix broken smoke test

- tests/smoke-actions.yaml
- tests/smoke-bundler-group-multidir.yaml
- tests/smoke-bundler-group-rules.yaml
- tests/smoke-bundler-group-vendoring.yaml
- tests/smoke-bundler-version-multidir.yaml
- tests/smoke-cargo-group-multidir.yaml
- tests/smoke-cargo-version-multidir.yaml
- tests/smoke-composer.yaml
- tests/smoke-docker-version-multidir.yaml
- tests/smoke-go-group-multidir.yaml
- tests/smoke-go-group-rules.yaml
- tests/smoke-go-group-security.yaml
- tests/smoke-go-update-security-multidir.yaml
- tests/smoke-go-update-version-multidir.yaml
- tests/smoke-go-version-multidir.yaml
- tests/smoke-gradle-group-multidir.yaml
- tests/smoke-gradle-version-multidir.yaml
- tests/smoke-maven-group-multidir.yaml
- tests/smoke-maven-version-multidir.yaml
- tests/smoke-npm-group-multidir.yaml
- tests/smoke-npm-group-multiple.yaml
- tests/smoke-npm-group-rules.yaml
- tests/smoke-npm-group-semver.yaml
- tests/smoke-npm-group-transitive.yaml
- tests/smoke-npm-version-multidir.yaml
- tests/smoke-nuget-group-multidir.yaml
- tests/smoke-nuget-version-multidir.yaml
- tests/smoke-python-group-multidir.yaml
- tests/smoke-python-version-multidir.yaml
We decided that the Updater (dependabot-core) would decide if the update is grouped, so no need to pass a grouped-update flag from the API.
> removes the unused grouped-update boolean

- .yamllint.yaml
The default values are `true` and `false`. Adding `on` to allow GitHub Actions workflow triggers to not flag.
| Before | After |
|--------|--------|
| https://github.com/dependabot/smoke-tests/pull/186 |https://github.com/dependabot/smoke-tests/pull/188 |
| <img width="1018" alt="image" src="https://github.com/dependabot/smoke-tests/assets/5278382/4a036f4a-a5ec-4403-8e42-3d954d475de9"> | <img width="970" alt="image" src="https://github.com/dependabot/smoke-tests/assets/5278382/16dfcbb8-4cfe-4a42-9e43-2718a8dffcc0"> |
> Allow `on` as a YAML key

- tests/smoke-go-group-security.yaml
- This PR is to fix the failing [go smoke test](https://github.com/dependabot/dependabot-core/actions/runs/8197962037/job/22420735945?pr=9240) in core for the mismatch in PR title. 
- Orignial PR which introduced this failing test: https://github.com/dependabot/dependabot-core/pull/9240
> Fix test to match correct PR title in Smoke test

- tests/smoke-nuget-central-package-management.yaml
- tests/smoke-nuget-potential-downgrade.yaml
- tests/smoke-nuget-resolvability.yaml
- tests/smoke-nuget-transitive-pinning.yaml
The file `Directory.Packages.props` is no longer explicitly listed as a dependency file.  This is due to the dependency ultimately needing to be declared in a `.csproj` file (or something imported by it) and it requires a value for the `<TargetFramework>` property, which a `Directory.Packages.props` file does not contain.
The resultant PR is still the same, though, and _may_ end up modifying the package version in `Directory.Packages.props`.
This corresponds to dependabot/dependabot-core#9347 and must be taken in parallel.
> update nuget smoke test dependency files

- tests/smoke-bundler-group-multidir.yaml
- tests/smoke-cargo-group-multidir.yaml
- tests/smoke-go-group-security.yaml
- tests/smoke-go-update-security-multidir.yaml
- tests/smoke-gradle-group-multidir.yaml
- tests/smoke-maven-group-multidir.yaml
- tests/smoke-npm-group-multidir.yaml
- tests/smoke-nuget-group-multidir.yaml
- tests/smoke-python-group-multidir.yaml
In theory these should all pass because it was implicit behavior before which is now being made explicit. 
The implicit behavior in the Updater is being removed here: https://github.com/dependabot/dependabot-core/pull/9506
> update multidir tests based on what the service sends

- tests/smoke-nuget-central-package-management.yaml
- tests/smoke-nuget-compatible-version.yaml
- tests/smoke-nuget-dirs-proj.yaml
- tests/smoke-nuget-group-multidir.yaml
- tests/smoke-nuget-peer-dependencies.yaml
- tests/smoke-nuget-potential-downgrade.yaml
- tests/smoke-nuget-props-and-targets.yaml
- tests/smoke-nuget-resolvability.yaml
- tests/smoke-nuget-sdk-implicit-deps.yaml
- tests/smoke-nuget-transitive-pinning.yaml
- tests/smoke-nuget-version-multidir.yaml
- tests/smoke-nuget-version-property.yaml
- tests/smoke-nuget.yaml
The NuGet updater reports its dependencies slightly differently now, so this PR needs to be taken in lock-step with:
* dependabot/dependabot-core#10025
The first change is that the full path of the dependency files is reported.  This is necessary because it's entirely possible in a multi-directory update for each directory to have a file with the same name, e.g., `Directory.Build.props`.  The earlier behavior of only reporting the file name could result in ambiguities in which file actually contained the relevant dependencies.
The second change is that we no longer report `nuspec_url` for each dependency because that value was simply transformed via the Ruby code into a repo URL (or project or license URL, in that order) and then eventually reported as `source_url`.  I instead do all of …
> update smoke tests to reflect nuget updater changes

- .github/workflows/smoke.yml
- tests/smoke-python-pip-compile.yaml
- tests/smoke-python-pip.yaml
This PR reverts the changes made in PR #212 that updated the smoke tests to match the revised "increase" versioning strategy for Python dependencies in Dependabot, as detailed in issue [#6631](https://github.com/dependabot/dependabot-core/issues/6631). The original update aligned the smoke tests with the changes introduced in Dependabot's main repository, which were reverted in PR #10194.
The changes in PR #212 were necessary to reflect the revised handling of version ranges in the pip ecosystem. However, due to the issues with the versioning strategy that prompted the revert of PR #10060, we need to revert the corresponding smoke tests to maintain consistency and ensure accurate testing.
- Related to issue #6631 on incorrect version range behavior.
- Follows discussions from issue #6625 …
> Revert PR #212: Update Smoke Tests for Python Dependencies Versioning Strategy

- nuget/top-level-only/dep-is-top-level/dep-is-top-level.csproj
- nuget/top-level-only/dep-is-transitive/dep-is-transitive.csproj
- nuget/top-level-only/top-level-only.sln
- tests/smoke-nuget-central-package-management.yaml
- tests/smoke-nuget-compatible-version.yaml
- tests/smoke-nuget-dirs-proj.yaml
- tests/smoke-nuget-group-multidir.yaml
- tests/smoke-nuget-peer-dependencies.yaml
- tests/smoke-nuget-potential-downgrade.yaml
- tests/smoke-nuget-props-and-targets.yaml
- tests/smoke-nuget-resolvability.yaml
- tests/smoke-nuget-sdk-implicit-deps.yaml
- tests/smoke-nuget-transitive-and-top-level-deps.yaml
- tests/smoke-nuget-transitive-pinning.yaml
- tests/smoke-nuget-version-multidir.yaml
- tests/smoke-nuget-version-property.yaml
- tests/smoke-nuget.yaml
This PR is in support of dependabot/dependabot-core#10449 and both will need to be merged at the same time.
> Add and update smoke tests for NuGet transitive dependency handling

- .github/workflows/smoke.yml
- tests/smoke-maven-group-multidir.yaml
Link to issue: https://github.com/dependabot/smoke-tests/issues/226
I've made a change to the order of maven versions in this PR: https://github.com/dependabot/dependabot-core/pull/10558 . Based on that change, which is based on the maven spec, version 1.5.11 == 1.5.11.RELEASE . Before this change, this test passed because it erroneously concluded that 1.5.11.RELEASE < 1.5.11.
> Bump version in maven security advisory

- .github/workflows/smoke.yml
- tests/smoke-maven-group-multidir.yaml
Reverts dependabot/smoke-tests#229
Link to issue: https://github.com/dependabot/smoke-tests/issues/226
I've made a change to how maven orders versions in this PR: https://github.com/dependabot/dependabot-core/pull/10558 . As a result, version 1.5.11 == 1.5.11.RELEASE . Before this change, this test passed because it erroneously concluded that 1.5.11.RELEASE < 1.5.11.
> Revert "Revert "Bump version in maven security advisory""

- tests/smoke-nuget-version-multidir.yaml
The packages `Microsoft.Extensions.Http` and `Microsoft.Extensions.Logging` recently pushed a new version `8.0.1` which breaks a smoke test.  This PR adds `ignore-condition` elements to restrict those.
> lock smoke test dependencies to specific version

- tests/smoke-python-version-multidir.yaml
This test started failing because some release notes changed. This indicates that the test wasn't fully cached.
So I've regenerated it and will recache it to prevent this from happening again.
> regenerate test that is failing

- tests/smoke-npm-yarn-berry-workspaces.yaml
[Removed the reference to the non-existing registry repo](https://github.com/dsp-testing/dependabot-core-smoke-yarn-monorepo/commit/d864e3910a2a5a237efa2733ec287db2ef4a8344) and created new sample repo for smoke test.
> Updating yarn-monorepo test sample repository.

- nuget/compatible-version/project/project.csproj
- tests/smoke-nuget-central-package-management.yaml
- tests/smoke-nuget-compatible-version.yaml
- tests/smoke-nuget-dirs-proj.yaml
- tests/smoke-nuget-lockfile.yaml
- tests/smoke-nuget-potential-downgrade.yaml
- tests/smoke-nuget-props-and-targets.yaml
- tests/smoke-nuget-transitive-pinning.yaml
- tests/smoke-nuget-version-property.yaml
This PR corresponds to dependabot/dependabot-core#11026 and both PRs need to go in at the same time.
This is expected to fail until the other PR has been merged.
> update smoke tests to use new reported file ordering

- tests/smoke-bundler.yaml
The Bundler registry that provides version information has changed, causing our smoke tests to fail. This Pull Request addresses the resulting issues, ensuring our pipeline runs successfully again.
For more details, please refer to the error log:
https://github.com/dependabot/dependabot-core/actions/runs/12404835515/job/34630668600?pr=11153
> Fix Smoke Tests for Bundler

- tests/smoke-bundler-group-multidir.yaml
- tests/smoke-bundler-group-rules.yaml
- tests/smoke-bundler-group-vendoring.yaml
Ruby 3.3.6 has json 2.7.2 as a default gem. See https://stdgems.org/json/.
This means that when upgrading Dependabot to use Ruby 3.3.6, even if smoke tests cache all network requests to keep the expected lockfile consistent, json will still resolve to 2.7.2 because even if the API only provides older (cached) versions, locally 2.7.2 is still available.
> Upgrade Bundler smoke tests for Ruby 3.3.6

- tests/smoke-composer.yaml
[Fix for this CI error](https://github.com/dependabot/dependabot-core/actions/runs/12733490542/job/35489929394?pr=6506),  after bumping to PHP8, I have noticed below changes in the smoke test file.
Related PR: https://github.com/dependabot/dependabot-core/pull/6506
> Fixing the smoke test error after bump to php8.

- tests/smoke-composer.yaml
Accidentally removed [this on previous PR](https://github.com/dependabot/smoke-tests/pull/245), Re adding credentials metadata
> Checking in credentials metadata

- tests/smoke-npm-group-multidir.yaml
- tests/smoke-npm-group-multiple.yaml
- tests/smoke-npm-group-rules.yaml
- tests/smoke-npm-group-semver.yaml
- tests/smoke-npm-group-transitive.yaml
- tests/smoke-npm-remove-transitive.yaml
- tests/smoke-npm-version-multidir.yaml
- tests/smoke-npm.yaml
Smoke test logs updated after corepack is removed from npm update.
These file changes will fix the smoke test failures on [this PR](https://github.com/dependabot/dependabot-core/pull/11299)
> Smoke test logs updated after corepack is removed from npm update.

- tests/smoke-npm-group-multidir.yaml
- tests/smoke-npm-group-multiple.yaml
- tests/smoke-npm-group-rules.yaml
- tests/smoke-npm-group-semver.yaml
- tests/smoke-npm-group-transitive.yaml
- tests/smoke-npm-remove-transitive.yaml
- tests/smoke-npm-version-multidir.yaml
- tests/smoke-npm.yaml
Reverts dependabot/smoke-tests#252
As per the discussion on 17/01/2025 standup we have agreed to move with the corepack removal and related updates.
Update to smoke tests results.yml as per the core pack removal.
> Revert "Reverting the smoketest related to corepack changes."

- nuget/sdk-implicit-deps/project.csproj
- nuget/transitive-pinning/project.csproj
- tests/smoke-nuget-sdk-implicit-deps.yaml
- tests/smoke-nuget-transitive-pinning.yaml
The 2 updated smoke tests were using cached network calls, but the cache was recently invalidated and in the time between the cache and now, new versions of the `Mongo2Go` package were released which caused the NuGet updater to update a top level dependency instead of pinning a transitive.
Because these two tests explicitly want to test transitive dependencies, we were able to be sneaky about it by updating the test projects to target `netstandard2.0` instead of `netcoreapp3.1` because that invalidates `Mongo2Go/4.0.0` forcing the test to remain on `3.1.3` like we want.
There was a bug in the NuGet updater where it wasn't considering the project's target framework, but that is fixed in the linked PR.
> update smoke tests for NuGet bug fix

- tests/smoke-npm-pnpm.yaml
This PR updates the smoke tests to align with the behavior after the removal of the `enable_fix_for_pnpm_no_change_error` feature flag.  
Although the feature flag had been enabled for the past two weeks, the smoke tests were still running without it. Now that the feature flag has been removed, the previously gated logic is the default behavior, and the smoke tests are now executing this code for the first time. As a result, adjustments were required to adapt the smoke tests to the new expected outputs.  
Related PRs: 
- https://github.com/dependabot/dependabot-core/pull/11592
- https://github.com/github/dependabot-api/pull/6267
- The `enable_fix_for_pnpm_no_change_error` feature flag was removed from **dependabot-core** and **dependabot-api**, making its logic the new default.  
- Smoke …
> Update Smoke Tests to Reflect Default Behavior After Feature Flag Removal

- pipenv/Pipfile
- pipenv/Pipfile.lock
- tests/smoke-python-pipenv.yaml
The pipenv smoke test has been failing as django requires asgiref which in turn requires python 3.8.1. Python 3.8 has been deprecated and correctly raises a tool-version-not supported error. To get around this issue, we have removed the django dependency and updated the numpy dependency to a newer version.
This change was reverted [earlier](https://github.com/dependabot/smoke-tests/pull/260) due to a dependabot-test directory that was deleted accidentally.
The failed checks in cargo-group-multidir and cargo-version-multidir are expected.
I've also ran [dependabot core tests](https://github.com/dependabot/dependabot-core/pull/11628) against this smoke test branch and the results are as expected.
> Remove django as it's subdependencies require deprecated python 3.8

- tests/smoke-cargo-group-multidir.yaml
- tests/smoke-cargo-version-multidir.yaml
Our cargo tests started failing when [rand 9.0.0 was released](https://github.com/rust-random/rand/releases/tag/0.9.0). This PR attempts to address this failure by making sure that we do not attempt to update rand to versions higher than the excepted one.
> Pin version of the rand to 0.8.5

- tests/smoke-cargo-group-multidir.yaml
- tests/smoke-cargo-version-multidir.yaml
Our cargo tests started failing when [rand 9.0.0 was released](https://github.com/rust-random/rand/releases/tag/0.9.0). This PR attempts to address this failure by making sure that we do not attempt to update `rand-core` to versions higher than the excepted one.
Thanks to @eggplants https://github.com/dependabot/smoke-tests/pull/265#issuecomment-2676219896 for suggesting this change
> Pin  to `rand-core` to `0.6.4`

- tests/smoke-npm-group-rules.yaml
- tests/smoke-npm-group-semver.yaml
- tests/smoke-npm.yaml
Our npm tests started failing when [get-intrinsic 1.3.0 was released](hhttps://www.npmjs.com/package/get-intrinsic/v/1.3.0). This PR attempts to address this failure by making sure that we do not attempt to update `get-intrinsic` to versions higher than `1.3.0`.
> Bumping get-intrinsic package

- tests/smoke-npm-group-rules.yaml
- tests/smoke-npm-group-semver.yaml
- tests/smoke-npm.yaml
This PR updates the NPM smoke tests to reflect the recent update of the `get-intrinsic` package from version **1.2.7** to **1.3.0**. The dependency changes affected the expected test output, requiring adjustments to maintain test accuracy. No functional changes were made—only test updates to align with the new dependency structure.
> Fix NPM Smoke Tests After `get-intrinsic` Dependency Update

- tests/smoke-devcontainers.yaml
- tests/smoke-submodules.yaml
Updating the smoke test results to exclude changes related to support files. Related PR: https://github.com/dependabot/dependabot-core/pull/11888
> Updating the smoke test results to exclude changes related to support files

- tests/smoke-bundler-security-subdep.yaml
I noticed this while looking at example security update... This should be pointing at our repo, not Deivid's personal copy of the repo.
Otherwise when he eventually deletes his copy, it'll break our tests.
> Don't rely on Deivid's copy of the smoke tests

- tests/smoke-nuget-compatible-version.yaml
- tests/smoke-nuget-lockfile.yaml
- tests/smoke-nuget-peer-dependencies.yaml
- tests/smoke-nuget-potential-downgrade.yaml
- tests/smoke-nuget-resolvability.yaml
- tests/smoke-nuget-version-multidir.yaml
All changes are reporting packages that weren't reported before because they are transitive dependencies with no runtime components like a `.dll` but the NuGet updater has been fixed to now report these packages.
> update smoke tests to include transitive packages with no active runtime components

- tests/smoke-python-poetry.yaml
This PR updates the smoke tests to reflect the behavior restored in https://github.com/dependabot/dependabot-core/pull/12431, where final releases (e.g. `0.45.0`) are correctly treated as distinct from preceding pre-releases (e.g. `0.45.0a1`).
The issue was originally tracked in https://github.com/dependabot/dependabot-core/issues/11902. This ensures the test suite now aligns with the intended fix and passes as expected.
> Fix smoke tests for pip latest version resolution after reverting uniq check

- .github/workflows/smoke.yml
- tests/smoke-npm-group-multidir.yaml
- tests/smoke-npm-version-multidir.yaml
This PR updates the npm_and_yarn smoke tests to reflect the behavior changes after removing the deprecated cooldown feature flag from the main Dependabot repository.
The main repository PR removed the cooldown feature flag for ecosystems: python, uv, npm_and_yarn, and bun. This change affected how dependency updates are processed, specifically impacting the handling of `left-pad` dependencies in our smoke tests.
The smoke tests were failing because they expected `left-pad` to be updated from version 1.0.0 to 1.3.0, but the actual behavior now shows that `left-pad` updates are being blocked due to ignore conditions (`>1.3.0` version requirement), resulting in `left-pad` staying at version 1.0.0.
- `tests/smoke-npm-group-multidir.yaml`
- `tests/smoke-npm-version-multidir.yaml`
1. **Removed …
> Update npm_and_yarn smoke tests after cooldown feature flag removal

- tests/smoke-npm-group-multidir.yaml
- tests/smoke-npm-version-multidir.yaml
We are reverting the update because that problem was causing for deprecated version (not yanked) and when we don't have feature flag smoke tests was hitting the logic where we are ignoring deprecated version. So we are reverting smoke test back and going to fix the logic properly
Reverts dependabot/smoke-tests#304
> Revert "Update npm_and_yarn smoke tests after cooldown feature flag removal"

- tests/smoke-composer.yaml
PR dependabot/dependabot-core#12570 updated composer from 2.7.7 to 2.8.9 and a [change](https://github.com/composer/composer/pull/12123) in composer 2.8.0 introduced a schema for the `composer.lock` file where `stability-flags`, `platform`, and `platform-dev` are now objects instead of arrays.
Swift failure is known and being tracked in dependabot/dependabot-core#12647
> update test to reflect tool update

- tests/smoke-nuget-central-package-management.yaml
- tests/smoke-nuget-compatible-version.yaml
- tests/smoke-nuget-dirs-proj.yaml
- tests/smoke-nuget-group-multidir.yaml
- tests/smoke-nuget-lockfile.yaml
- tests/smoke-nuget-peer-dependencies.yaml
- tests/smoke-nuget-potential-downgrade.yaml
- tests/smoke-nuget-props-and-targets.yaml
- tests/smoke-nuget-resolvability.yaml
- tests/smoke-nuget-sdk-implicit-deps.yaml
- tests/smoke-nuget-sdk-replacement-packages.yaml
- tests/smoke-nuget-transitive-and-top-level-deps.yaml
- tests/smoke-nuget-transitive-pinning.yaml
- tests/smoke-nuget-version-multidir.yaml
- tests/smoke-nuget-version-property.yaml
- tests/smoke-nuget.yaml
The NuGet updater will soon generate more details in the pull request body but while that work is happening, the smoke tests are being updated to force the simple version to avoid churn.
Once the detailed PR body work is done, the smoke tests will be updated to contain the full information.
The experiment flag used isn't registered with the dependabot service, it's purely a mechanism to force these short versions while work is ongoing.
> generate simple pr body while other refactorings are underway

- tests/smoke-npm-group-rules.yaml
- tests/smoke-npm-group-semver.yaml
- tests/smoke-npm.yaml
Updates npm smoke test configurations to accept form-data dependency updates to 4.0.4, ensuring consistent test results across different environments.
- **Removed form-data ignore conditions** from all three npm smoke test files:
- `tests/smoke-npm.yaml`
- `tests/smoke-npm-group-rules.yaml` 
- `tests/smoke-npm-group-semver.yaml`
- **Regenerated smoke test expectations** using `dependabot test -f <file> -o <file>` to accept form-data 4.0.4 updates
- **Updated commit SHAs** to latest branch state (d15ce2f331fa91f5ebb82da530dc7f3d69c64e6e)
Previously, the smoke tests had ignore conditions that attempted to prevent form-data from updating beyond version 4.0.3:
> Update npm smoke tests to accept form-data 4.0.4 dependency updates

- tests/smoke-nuget-dirs-proj.yaml
A follow up to https://github.com/dependabot/dependabot-core/pull/12962, this updates the smoke tests.
Failing Swift test is due to https://github.com/dependabot/dependabot-core/issues/12647
> update title and commit message to include more information

- tests/smoke-swift.yaml
- tests/smoke-vcpkg-builtin-baseline.yaml
Based on code analysis, the dependency name must follow the pattern `github.com/mattgallagher/cwlpreconditiontesting` to ensure correct resolution. Using only `cwlpreconditiontesting` will not match the ignore condition as expected.
The `Dependabot::Dependency` object confirms this naming convention:
```
@name="github.com/mattgallagher/cwlpreconditiontesting"
@metadata={identity: "cwlpreconditiontesting"}
```
Additionally, the `Package.swift` manifest should align with this naming pattern to maintain consistency and ensure proper dependency resolution.
**Note:** 
Ignore conditions are applicable **only to direct dependencies**, such as:
- `github.com/reactivecocoa/reactiveswift` 
- `github.com/quick/quick` 
- `github.com/quick/nimble`
and it's not applicable transitive/secondary …
> Fixing swift smoke tests error
